Repository Thenlie/pathfinder, pull requests merged in 2022-09, with the labels that each got.

#42 39 refactor/dynamic length width
  src/components/Generator.vue
  src/components/Maze.vue
  src/lib/mazeArray.js
  src/views/About.vue
  src/views/Home.vue
Labels: type: enhancement, type: styling, type: refactor

#43 Limited inputs to 5-50
  src/views/Home.vue
Labels: type: enhancement, type: refactor

#44 38 solver/animation
  src/components/Solver.vue
  src/utils/mazeUtil.js
  src/views/Home.vue
Labels: type: enhancement, type: styling
