Repository Thenlie/pathfinder, pull requests merged in 2022-08, with the labels that each got.

#11 [10] Generator: 2D Array
  src/App.vue
  src/components/Generator.vue
Labels: type: enhancement, type: refactor

#14 [12] Generator: Utilities
  src/components/Generator.vue
  src/utils/arrayUtil.js
  src/utils/mazeUtil.js
Labels: type: enhancement, type: refactor

#16 [15] Generator: Testing Framework
  package-lock.json
  package.json
  src/__tests__/arrayUtil.test.js
Labels: type: enhancement

#18 Update README.md
  README.md
Labels: type: documentation

#19 17 generator/recursion
  src/App.vue
  src/__tests__/arrayUtil.test.js
  src/components/NewGenerator.vue
  src/lib/MazeCell.js
  src/style.css
  src/utils/arrayUtil.js
Labels: type: enhancement, type: refactor

#23 22 feature/pages
  package-lock.json
  package.json
  src/App.vue
  src/__tests__/arrayUtil.test.js
  src/components/Dots.vue
  src/components/Generator.vue
  src/components/Maze.vue
  src/components/Navigation.vue
  src/components/NewGenerator.vue
  src/main.js
  src/style.css
  src/utils/arrayUtil.js
  src/utils/mazeUtil.js
  src/views/About.vue
  src/views/Home.vue
Labels: type: enhancement, type: styling, type: component

#25 24 feature/about
  package-lock.json
  package.json
  src/App.vue
  src/components/Generator.vue
  src/components/SampleMaze.vue
  src/components/TestMaze.vue
  src/main.js
  src/style.css
  src/test-maze.js
  src/utils/mazeUtil.js
  src/utils/testMaze.js
  src/views/About.vue
  src/views/Home.vue
  vite.config.js
Labels: type: documentation, type: styling, type: component

#28 26 feature/maze component
  src/components/Generator.vue
  src/components/Maze.vue
  src/components/SampleMazes.vue
  src/components/TestMaze.vue
  src/utils/mazeUtil.js
  src/views/About.vue
  src/views/Home.vue
Labels: type: enhancement, type: refactor

#31 29 feature/footer
  README.md
  src/App.vue
  src/components/Dots.vue
  src/components/Footer.vue
  src/components/Generator.vue
  src/components/Maze.vue
  src/main.js
  src/style.css
  src/views/About.vue
  src/views/Home.vue
Labels: type: styling, type: component

#32 Branch 6 Update
  README.md
  package-lock.json
  package.json
  src/App.vue
  src/__tests__/arrayUtil.test.js
  src/components/Dots.vue
  src/components/Footer.vue
  src/components/Generator.vue
  src/components/Maze.vue
  src/components/Navigation.vue
  src/components/SampleMazes.vue
  src/lib/MazeCell.js
  src/main.js
  src/style.css
  src/utils/arrayUtil.js
  src/utils/mazeUtil.js
  src/utils/testMaze.js
  src/views/About.vue
  src/views/Home.vue
  vite.config.js
Labels: type: refactor

#33 6 solving/first solve
  src/components/Generator.vue
  src/components/Solver.vue
  src/utils/arrayUtil.js
  src/utils/mazeUtil.js
  src/views/Home.vue
Labels: type: enhancement, type: component

#36 Bug/deployed state
  src/components/Generator.vue
  src/components/Solver.vue
  src/lib/mazeArray.js
  src/views/About.vue
  src/views/Home.vue
Labels: type: bug, type: refactor

#37 Update README.md
  README.md
Labels: type: documentation, type: enhancement

#41 minor refactor of Solver to clean up unnecessary code
  src/components/Solver.vue
  src/views/Home.vue
Labels: type: refactor
